# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image_one',
            field=models.ImageField(default='item_pictures/None/no-img.jpg', upload_to='item_pictures/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_three',
            field=models.ImageField(blank=True, default='item_pictures/None/no-img.jpg', upload_to='item_pictures/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_two',
            field=models.ImageField(blank=True, default='item_pictures/None/no-img.jpg', upload_to='item_pictures/'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
