# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 18:38
from __future__ import unicode_literals

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190325_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isUsed',
        ),
        migrations.AlterField(
            model_name='item',
            name='image_one',
            field=models.ImageField(default='item_pictures/None/no-img.jpg', upload_to=apps.store.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_three',
            field=models.ImageField(blank=True, default='item_pictures/None/no-img.jpg', upload_to=apps.store.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_two',
            field=models.ImageField(blank=True, default='item_pictures/None/no-img.jpg', upload_to=apps.store.models.path_and_rename),
        ),
    ]
