# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190326_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_status', models.IntegerField(choices=[(0, 'Not Paid'), (2, 'Partial Paid'), (1, 'Paid')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buyer', to='store.User')),
                ('items', models.ManyToManyField(related_name='orders', to='store.Item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller', to='store.User')),
            ],
        ),
    ]
